'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Automatische My.Settings-Speicherfunktion"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\Packages\HC\")>  _
        Public Property Hashcat() As String
            Get
                Return CType(Me("Hashcat"),String)
            End Get
            Set
                Me("Hashcat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\Packages\JtR\run\")>  _
        Public Property JTR() As String
            Get
                Return CType(Me("JTR"),String)
            End Get
            Set
                Me("JTR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\Packages\Py2\App\Python\PP2.exe")>  _
        Public Property PP2() As String
            Get
                Return CType(Me("PP2"),String)
            End Get
            Set
                Me("PP2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\Packages\Py3\App\Python\PP3.exe")>  _
        Public Property PP3() As String
            Get
                Return CType(Me("PP3"),String)
            End Get
            Set
                Me("PP3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\Packages\Perl\perl\bin\perl_hashbull.exe")>  _
        Public Property Perl() As String
            Get
                Return CType(Me("Perl"),String)
            End Get
            Set
                Me("Perl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\Packages\BuEx\bulk_extractor64.exe")>  _
        Public Property Bulk() As String
            Get
                Return CType(Me("Bulk"),String)
            End Get
            Set
                Me("Bulk") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property GPUonly() As Boolean
            Get
                Return CType(Me("GPUonly"),Boolean)
            End Get
            Set
                Me("GPUonly") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MinControll() As Boolean
            Get
                Return CType(Me("MinControll"),Boolean)
            End Get
            Set
                Me("MinControll") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Force() As Boolean
            Get
                Return CType(Me("Force"),Boolean)
            End Get
            Set
                Me("Force") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3 - Speed")>  _
        Public Property Workload() As String
            Get
                Return CType(Me("Workload"),String)
            End Get
            Set
                Me("Workload") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("85")>  _
        Public Property Celsius() As String
            Get
                Return CType(Me("Celsius"),String)
            End Get
            Set
                Me("Celsius") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-O ")>  _
        Public Property OtherPara() As String
            Get
                Return CType(Me("OtherPara"),String)
            End Get
            Set
                Me("OtherPara") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CheckPot() As Boolean
            Get
                Return CType(Me("CheckPot"),Boolean)
            End Get
            Set
                Me("CheckPot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CheckHelp6() As Boolean
            Get
                Return CType(Me("CheckHelp6"),Boolean)
            End Get
            Set
                Me("CheckHelp6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CheckHelp7() As Boolean
            Get
                Return CType(Me("CheckHelp7"),Boolean)
            End Get
            Set
                Me("CheckHelp7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property TimerS() As String
            Get
                Return CType(Me("TimerS"),String)
            End Get
            Set
                Me("TimerS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property fav() As String
            Get
                Return CType(Me("fav"),String)
            End Get
            Set
                Me("fav") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DevOnly() As String
            Get
                Return CType(Me("DevOnly"),String)
            End Get
            Set
                Me("DevOnly") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Eng() As Boolean
            Get
                Return CType(Me("Eng"),Boolean)
            End Get
            Set
                Me("Eng") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Ger() As Boolean
            Get
                Return CType(Me("Ger"),Boolean)
            End Get
            Set
                Me("Ger") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("_Encoding_OFF")>  _
        Public Property Encoding() As String
            Get
                Return CType(Me("Encoding"),String)
            End Get
            Set
                Me("Encoding") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CheckHelp1() As Boolean
            Get
                Return CType(Me("CheckHelp1"),Boolean)
            End Get
            Set
                Me("CheckHelp1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Mail() As String
            Get
                Return CType(Me("Mail"),String)
            End Get
            Set
                Me("Mail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MailAct() As Boolean
            Get
                Return CType(Me("MailAct"),Boolean)
            End Get
            Set
                Me("MailAct") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("blockchain.com")>  _
        Public Property Scanner1() As String
            Get
                Return CType(Me("Scanner1"),String)
            End Get
            Set
                Me("Scanner1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("binance.com")>  _
        Public Property Scanner2() As String
            Get
                Return CType(Me("Scanner2"),String)
            End Get
            Set
                Me("Scanner2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("bitwala.com")>  _
        Public Property Scanner3() As String
            Get
                Return CType(Me("Scanner3"),String)
            End Get
            Set
                Me("Scanner3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("kraken.com")>  _
        Public Property Scanner4() As String
            Get
                Return CType(Me("Scanner4"),String)
            End Get
            Set
                Me("Scanner4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("getmonero.org")>  _
        Public Property Scanner5() As String
            Get
                Return CType(Me("Scanner5"),String)
            End Get
            Set
                Me("Scanner5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("coinbase.com")>  _
        Public Property Scanner6() As String
            Get
                Return CType(Me("Scanner6"),String)
            End Get
            Set
                Me("Scanner6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("bitpanda.com")>  _
        Public Property Scanner7() As String
            Get
                Return CType(Me("Scanner7"),String)
            End Get
            Set
                Me("Scanner7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("myetherwallet.com")>  _
        Public Property Scanner8() As String
            Get
                Return CType(Me("Scanner8"),String)
            End Get
            Set
                Me("Scanner8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ledger.com")>  _
        Public Property Scanner9() As String
            Get
                Return CType(Me("Scanner9"),String)
            End Get
            Set
                Me("Scanner9") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Trezor")>  _
        Public Property Scanner10() As String
            Get
                Return CType(Me("Scanner10"),String)
            End Get
            Set
                Me("Scanner10") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("trezor.io")>  _
        Public Property Scanner11() As String
            Get
                Return CType(Me("Scanner11"),String)
            End Get
            Set
                Me("Scanner11") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("shapeshift.com")>  _
        Public Property Scanner12() As String
            Get
                Return CType(Me("Scanner12"),String)
            End Get
            Set
                Me("Scanner12") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("KeepKey")>  _
        Public Property Scanner13() As String
            Get
                Return CType(Me("Scanner13"),String)
            End Get
            Set
                Me("Scanner13") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Scanner14() As String
            Get
                Return CType(Me("Scanner14"),String)
            End Get
            Set
                Me("Scanner14") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Scanner15() As String
            Get
                Return CType(Me("Scanner15"),String)
            End Get
            Set
                Me("Scanner15") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Scanner16() As String
            Get
                Return CType(Me("Scanner16"),String)
            End Get
            Set
                Me("Scanner16") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("*bitcoin*.exe")>  _
        Public Property Scanner17() As String
            Get
                Return CType(Me("Scanner17"),String)
            End Get
            Set
                Me("Scanner17") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("wallet.dat")>  _
        Public Property Scanner18() As String
            Get
                Return CType(Me("Scanner18"),String)
            End Get
            Set
                Me("Scanner18") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("*.wallet")>  _
        Public Property Scanner19() As String
            Get
                Return CType(Me("Scanner19"),String)
            End Get
            Set
                Me("Scanner19") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("*electrum*.exe")>  _
        Public Property Scanner20() As String
            Get
                Return CType(Me("Scanner20"),String)
            End Get
            Set
                Me("Scanner20") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("*ethereum*.exe")>  _
        Public Property Scanner21() As String
            Get
                Return CType(Me("Scanner21"),String)
            End Get
            Set
                Me("Scanner21") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("*monero*.exe")>  _
        Public Property Scanner22() As String
            Get
                Return CType(Me("Scanner22"),String)
            End Get
            Set
                Me("Scanner22") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("*exodus*.exe")>  _
        Public Property Scanner23() As String
            Get
                Return CType(Me("Scanner23"),String)
            End Get
            Set
                Me("Scanner23") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("*ledger*.*")>  _
        Public Property Scanner24() As String
            Get
                Return CType(Me("Scanner24"),String)
            End Get
            Set
                Me("Scanner24") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C D E F G H I J K L M N O P Q R S T U V W X Y Z")>  _
        Public Property EFSDrives() As String
            Get
                Return CType(Me("EFSDrives"),String)
            End Get
            Set
                Me("EFSDrives") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EFS7() As Boolean
            Get
                Return CType(Me("EFS7"),Boolean)
            End Get
            Set
                Me("EFS7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EFS2() As Boolean
            Get
                Return CType(Me("EFS2"),Boolean)
            End Get
            Set
                Me("EFS2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EFS3() As Boolean
            Get
                Return CType(Me("EFS3"),Boolean)
            End Get
            Set
                Me("EFS3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EFS4() As Boolean
            Get
                Return CType(Me("EFS4"),Boolean)
            End Get
            Set
                Me("EFS4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EFS5() As Boolean
            Get
                Return CType(Me("EFS5"),Boolean)
            End Get
            Set
                Me("EFS5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EFS6() As Boolean
            Get
                Return CType(Me("EFS6"),Boolean)
            End Get
            Set
                Me("EFS6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CopyFolder() As String
            Get
                Return CType(Me("CopyFolder"),String)
            End Get
            Set
                Me("CopyFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Checklog() As Boolean
            Get
                Return CType(Me("Checklog"),Boolean)
            End Get
            Set
                Me("Checklog") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ClientIP() As String
            Get
                Return CType(Me("ClientIP"),String)
            End Get
            Set
                Me("ClientIP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ClientPort() As String
            Get
                Return CType(Me("ClientPort"),String)
            End Get
            Set
                Me("ClientPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ClientPW() As String
            Get
                Return CType(Me("ClientPW"),String)
            End Get
            Set
                Me("ClientPW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ClientFeat() As String
            Get
                Return CType(Me("ClientFeat"),String)
            End Get
            Set
                Me("ClientFeat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ServerIP() As String
            Get
                Return CType(Me("ServerIP"),String)
            End Get
            Set
                Me("ServerIP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ServerPort() As String
            Get
                Return CType(Me("ServerPort"),String)
            End Get
            Set
                Me("ServerPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ServerPW() As String
            Get
                Return CType(Me("ServerPW"),String)
            End Get
            Set
                Me("ServerPW") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BrainCheck() As Boolean
            Get
                Return CType(Me("BrainCheck"),Boolean)
            End Get
            Set
                Me("BrainCheck") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MailCheck() As Boolean
            Get
                Return CType(Me("MailCheck"),Boolean)
            End Get
            Set
                Me("MailCheck") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Hashbull.My.MySettings
            Get
                Return Global.Hashbull.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
